fix syntax error

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -14,31 +14,30 @@ variables:
   - &verify-core-dependencies
     name: Verify Core Dependencies
     command: |
-      command: |
-            SFDX_CLI_VERSION="$(docker run -it --rm $DOCKER_IMAGE:$TAG bash -c 'sfdx --version')"
-            JAVA_VERSION="$(docker run -it --rm $DOCKER_IMAGE:$TAG bash -c 'java --version | head -n 1')"
-            NODE_VERSION="$(docker run -it --rm $DOCKER_IMAGE:$TAG bash -c 'node -v')"
-            if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
-            then
-              echo "sfdx-cli installed -" $SFDX_CLI_VERSION 
-            else
-              echo "The sfdx-cli installation could not be verified"
-              exit 1
-            fi
-            if [[ ((`echo $JAVA_VERSION | grep -c "openjdk 11.0.4"` > 0))]]
-            then
-             echo "Java installed -" $JAVA_VERSION 
-            else
-              echo "The Java installation could not be verified"
-              exit 1
-            fi
-            if [[ ((`echo $NODE_VERSION | grep -c "v10.16.2"` > 0))]]
-            then
-             echo "Node installed -" $NODE_VERSION 
-            else
-              echo "The Node installation could not be verified"
-              exit 1
-            fi
+      SFDX_CLI_VERSION="$(docker run -it --rm $DOCKER_IMAGE:$TAG bash -c 'sfdx --version')"
+      JAVA_VERSION="$(docker run -it --rm $DOCKER_IMAGE:$TAG bash -c 'java --version | head -n 1')"
+      NODE_VERSION="$(docker run -it --rm $DOCKER_IMAGE:$TAG bash -c 'node -v')"
+      if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
+      then
+        echo "sfdx-cli installed -" $SFDX_CLI_VERSION 
+      else
+        echo "The sfdx-cli installation could not be verified"
+        exit 1
+      fi
+      if [[ ((`echo $JAVA_VERSION | grep -c "openjdk 11.0.4"` > 0))]]
+      then
+        echo "Java installed -" $JAVA_VERSION 
+      else
+        echo "The Java installation could not be verified"
+        exit 1
+      fi
+      if [[ ((`echo $NODE_VERSION | grep -c "v10.16.2"` > 0))]]
+      then
+        echo "Node installed -" $NODE_VERSION 
+      else
+        echo "The Node installation could not be verified"
+        exit 1
+      fi
   - &verify-add-on-utilities
     name: Verify Add-On Utilities
     command: |
